name: faceformer
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cudatoolkit=11.0.221
  - jpeg=9b
  - json5=0.9.6
  - pillow=8.2.0
  - python=3.7.10
  - pythonocc-core=7.4.1
  - pythreejs=2.3.0
  - pytorch=1.7.1
  - pip=21.1.3
  - pip:
    - async-timeout==3.0.1
    - cairosvg==2.5.2
    - cvxpy==1.1.17
    - easydict==1.9
    - h5py==3.1.0
    - html4vision==0.4.3
    - matplotlib==3.4.2
    - numpy==1.19.5
    - numpyencoder==0.3.0
    - open3d==0.13.0
    - opencv-python==4.5.2.54
    - pytorch-lightning==1.3.5
    - pyyaml==5.4.1
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - svgwrite==1.4.1
    - timeout-decorator==0.5.0
    - torchmetrics==0.3.2
    - tqdm==4.61.1
    - trimesh==3.9.20
    - CairoSVG==2.5.2
    - fvcore==0.1.5.post20210617