# Each face as a seq with fixed viewpoint

# dataset generation method:  
# python dataset/prepare_data.py ... --focus 0

model_class: 'SurfaceFormer_Parallel'
dataset_class: 'ABCDataset_Parallel'
root_dir: "test_set/ours-fixed_viewpoint"

batch_size_train: 4
batch_size_valid: 20

trainer:
  name: 'SurfaceFormer'
  version: 'ours-fixed_viewpoint'
  lr: 1.0e-4
  num_gpus: [0]
  
model:
  num_lines: 186
  max_num_faces: 42
  max_face_length: 33
  token:
    PAD: 0
    face_type_offset: 1
    len: 4